// <auto-generated />
using System;
using EntityFrameworkIssueExample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkIssueExample.Migrations
{
    [DbContext(typeof(EntityFrameworkDbContext))]
    [Migration("20181110142713_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkIssueExample.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AddedByAccountId");

                    b.Property<DateTime>("AddedOnUtc");

                    b.Property<Guid?>("ModifiedByAccountId");

                    b.Property<DateTime>("ModifiedOnUtc");

                    b.HasKey("AccountId");

                    b.HasIndex("AddedByAccountId");

                    b.HasIndex("ModifiedByAccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EntityFrameworkIssueExample.Entities.Account", b =>
                {
                    b.HasOne("EntityFrameworkIssueExample.Entities.Account", "AddedByAccount")
                        .WithOne()
                        .HasForeignKey("EntityFrameworkIssueExample.Entities.Account", "AddedByAccountId");

                    b.HasOne("EntityFrameworkIssueExample.Entities.Account", "ModifiedByAccount")
                        .WithMany()
                        .HasForeignKey("ModifiedByAccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
